// The mutation-testing tooling (#280) — tool/mutation.sh + tool/mutation_report.py.
//
// Mutation testing is how this repo checks that its tests would NOTICE a
// broken line, so the tooling itself has two failure modes that would make the
// whole exercise theatre:
//
//   - THE PARSER STOPS SEEING SURVIVORS. mutation_test writes its report as
//     markdown with inline HTML; the survivor text is a nested <span> pair, and
//     a mutant that spans source lines carries real newlines inside it. If the
//     extraction quietly returns nothing (a regex that eats a Dart `<=` as if
//     it were a tag, a shape change in a tool upgrade), every file reports zero
//     survivors, the ratchet is permanently green, and nobody notices that the
//     suite noticed nothing.
//   - THE RATCHET DOES NOT BITE. The baseline exists so a file can never grow
//     survivors. If exceeding it still exits 0, a run "passes" while the tests
//     have stopped catching mutants they used to catch.
//
// and one that would make its results meaningless:
//
//   - THE WRONG TESTS RUN. Each source file is mutated against its OWN tests
//     for speed. Scope the mutants of engine.dart to test/model and every
//     mutant "survives" — a number that says nothing about the suite. The plan
//     mode is asserted here so a scoping change is visible as a test failure.
//
// These drive the real scripts as a user does (bash / python3, exit codes,
// stdout, the written TSV) — no mutation run, so the file is fast and offline.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// A verbatim-shaped mutation_test 1.8.0 markdown report: two listed survivors
/// (one of them multi-line) and a third undetected mutant that no test covers
/// at all — exactly the split the real backup.dart report has, where the
/// "Undetected" total exceeds the number of listed mutants.
const _report = r'''
# Mutation report
This is a mutation report generated by mutation-test version: 1.8.0

2026-09-04 13:49:45.654961

| Key           | Value                     |
| ------------- | ------------------------- |
| Rules         | mutation-config.xml           |
| Rules         | Builtin Rules           |
| Mutations     | 37                        |
| Elapsed     | 0:03:57.809146                        |
| Timeouts      | 0                        |
| Not covered by tests | 1                        |
| Undetected    | 3                        |
| Undetected%   | 8.11%                        |
| Detected by: test            | 34         |
| Quality Rating | B |
| Success | true |


## Undetected mutations in file : lib/src/model/effective_due.dart
Line 53:<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: rgb(255, 200, 200);">-   return a.compareTo(b) <span style="background-color: rgb(255, 50, 50);"><=</span> 0 ? a : b;</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: rgb(200, 255, 200);">+   return a.compareTo(b) <span style="background-color: rgb(50, 255, 50);"><</span> 0 ? a : b;</span><br>
Line 87:<br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: rgb(255, 200, 200);">-     <span style="background-color: rgb(255, 50, 50);">}

    seen.remove(t.id);</span></span><br>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: rgb(200, 255, 200);">+     <span style="background-color: rgb(50, 255, 50);">}

    </span></span><br>
''';

/// The same report shape for a file the suite killed everything in: the tool
/// emits the section header with nothing under it.
const _cleanReport = r'''
# Mutation report
This is a mutation report generated by mutation-test version: 1.8.0

| Key           | Value                     |
| ------------- | ------------------------- |
| Mutations     | 121                        |
| Elapsed     | 0:14:45.468983                        |
| Timeouts      | 0                        |
| Not covered by tests | 0                        |
| Undetected    | 0                        |
| Detected by: test            | 121         |
| Success | true |


## Undetected mutations in file : lib/src/store/backup.dart
''';

late Directory _dir;

/// Report dir + baseline written fresh per test, so nothing leaks between them.
String _fixture(String reportName, String reportBody, String baseline) {
  File('${_dir.path}/$reportName').writeAsStringSync(reportBody);
  File('${_dir.path}/baseline.tsv').writeAsStringSync(baseline);
  return _dir.path;
}

ProcessResult _summarise(List<String> args) =>
    Process.runSync('python3', ['tool/mutation_report.py', ...args]);

void main() {
  setUp(() => _dir = Directory.systemTemp.createTempSync('mutation_report'));
  tearDown(() => _dir.deleteSync(recursive: true));

  test('the survivor list carries the mutant a human has to judge', () {
    final dir = _fixture(
      'effective_due.md',
      _report,
      'lib/src/model/effective_due.dart\t3\n',
    );
    final tsv = '$dir/survivors.tsv';

    final run = _summarise([
      '--baseline',
      '$dir/baseline.tsv',
      '--tsv',
      tsv,
      dir,
    ]);

    expect(run.exitCode, 0, reason: '3 survivors, baseline 3: ${run.stdout}');
    // The counts a human reads: 37 mutants, 3 undetected, 1 of them uncovered.
    expect(
      (run.stdout as String)
          .split('\n')
          .firstWhere((l) => l.startsWith('lib/src/model/effective_due.dart')),
      matches(RegExp(r'\s37\s+3\s+1\s+0\s+3\s+0:03:57')),
    );
    // Each listed mutant survives as one TSV row — the operator triages it by
    // reading the original against the mutated text, so both must be intact.
    // The `<=` is the load-bearing character of row one: it is what a blunt
    // tag-stripper deletes, leaving a "survivor" nobody can classify.
    expect(File(tsv).readAsLinesSync(), [
      'file\tline\toriginal\tmutated',
      'lib/src/model/effective_due.dart\t53\t'
          'return a.compareTo(b) <= 0 ? a : b;\t'
          'return a.compareTo(b) < 0 ? a : b;',
      'lib/src/model/effective_due.dart\t87\t'
          r'}\n\nseen.remove(t.id);'
          '\t}',
    ]);
  });

  test('a file over its baseline fails the run and names both numbers', () {
    final dir = _fixture(
      'effective_due.md',
      _report,
      '# seeded from the pilot\nlib/src/model/effective_due.dart\t2\n',
    );

    final run = _summarise(['--baseline', '$dir/baseline.tsv', dir]);

    expect(run.exitCode, 1);
    expect(
      run.stdout,
      contains(
        'RATCHET FAILED: lib/src/model/effective_due.dart has 3 survivors, '
        'baseline 2',
      ),
    );
    // ...and says what closing it means, because the cheap way out is to edit
    // the number back.
    expect(run.stdout, contains('never by excluding the line'));
  });

  test('a file with no survivors reports a clean run, not a parse failure', () {
    final dir = _fixture(
      'backup.md',
      _cleanReport,
      'lib/src/store/backup.dart\t7\n',
    );
    final tsv = '$dir/survivors.tsv';

    final run = _summarise([
      '--baseline',
      '$dir/baseline.tsv',
      '--tsv',
      tsv,
      dir,
    ]);

    expect(run.exitCode, 0);
    expect(
      (run.stdout as String)
          .split('\n')
          .firstWhere((l) => l.startsWith('lib/src/store/backup.dart')),
      matches(RegExp(r'\s121\s+0\s+0\s+0\s+7\s')),
    );
    expect(File(tsv).readAsLinesSync(), ['file\tline\toriginal\tmutated']);
  });

  test('a report whose survivors went missing is a failure, not a clean run', () {
    // The listing is the only place a survivor can be judged. If the extraction
    // silently returns fewer mutants than the header counted — a tool upgrade
    // that moves the markup, a regex that stops matching — the table would show
    // survivors nobody can see and the TSV would be short, quietly. Only
    // mutants NO test covers are legitimately unlisted, and the report counts
    // those separately.
    final dir = _fixture(
      'effective_due.md',
      _report.replaceFirst(
        '| Not covered by tests | 1 ',
        '| Not covered by tests | 0 ',
      ),
      'lib/src/model/effective_due.dart\t3\n',
    );

    final run = _summarise(['--baseline', '$dir/baseline.tsv', dir]);

    expect(run.exitCode, 1);
    expect(
      run.stdout,
      contains('3 undetected mutants but only 2 could be read'),
    );
  });

  test('a mutant that HUNG the suite is counted, not called a parse failure', () {
    // A mutant can also survive by never returning: mutation_test kills the
    // test command at the timeout, counts the mutant undetected, and writes no
    // text for it — the same shape as an uncovered one. reconcile.dart
    // produces exactly this (`var progressed = false` flipped to `true` in
    // orderParentsFirst loops forever), so charging the difference to the
    // parser would make every run of that file exit "CANNOT READ" and no
    // reconcile number could ever be trusted again.
    final dir = _fixture(
      'effective_due.md',
      _report
          .replaceFirst('| Undetected    | 3 ', '| Undetected    | 4 ')
          .replaceFirst('| Timeouts      | 0 ', '| Timeouts      | 1 '),
      'lib/src/model/effective_due.dart\t4\n',
    );

    final run = _summarise(['--baseline', '$dir/baseline.tsv', dir]);

    expect(run.exitCode, 0, reason: run.stdout as String);
    expect(run.stdout, isNot(contains('CANNOT READ')));
    // The timeout is still visible in the table — it is a survivor a human has
    // to account for, just not one the report can quote.
    expect(
      (run.stdout as String)
          .split('\n')
          .firstWhere((l) => l.startsWith('lib/src/model/effective_due.dart')),
      matches(RegExp(r'\s37\s+4\s+1\s+1\s+4\s')),
    );
  });

  test('a file with no baseline entry is flagged, not silently ratcheted', () {
    final dir = _fixture('effective_due.md', _report, '# nothing listed\n');

    final run = _summarise(['--baseline', '$dir/baseline.tsv', dir]);

    expect(run.exitCode, 0);
    expect(
      run.stdout,
      contains('note: lib/src/model/effective_due.dart has no baseline entry'),
    );
  });

  test('the committed ratchet only lists files that still exist', () {
    final entries = File('tool/mutation_baseline.tsv')
        .readAsLinesSync()
        .map((l) => l.split('#').first.trim())
        .where((l) => l.isNotEmpty)
        .toList();

    expect(entries, isNotEmpty, reason: 'an empty ratchet gates nothing');
    for (final entry in entries) {
      final fields = entry.split('\t');
      expect(fields, hasLength(2), reason: 'malformed baseline row: $entry');
      // A renamed or deleted source leaves an entry that can never be
      // exceeded — the file it used to guard silently stops being ratcheted.
      expect(
        File(fields[0]).existsSync(),
        isTrue,
        reason: '${fields[0]} is in the ratchet but not in the repository',
      );
      expect(int.tryParse(fields[1]), isNotNull);
    }
  });

  group('mutation.sh scopes each source file to the tests that cover it', () {
    ProcessResult plan(List<String> sources) =>
        Process.runSync('bash', ['tool/mutation.sh', '--plan', ...sources]);

    test('a model file runs its own test first, then its importers', () {
      final run = plan(['lib/src/model/dates.dart']);

      expect(run.exitCode, 0, reason: run.stderr as String);
      final line = (run.stdout as String).trim();
      expect(
        line,
        startsWith(
          'lib/src/model/dates.dart: flutter test test/model/dates_test.dart',
        ),
      );
      // The quick-date menu is where DateMove reaches the user; a mutant in
      // dates.dart that only that surface can catch must be in scope.
      expect(line, contains('test/ui/quick_date_menu_test.dart'));

      final files = line.split(' flutter test ').last.split(' ');
      expect(
        files.length,
        lessThanOrEqualTo(9),
        reason:
            'same-name test + at most 8 importers, or one widely imported '
            'file drags the whole suite into every mutant run',
      );
      for (final file in files) {
        expect(file, endsWith('_test.dart'));
        expect(File(file).existsSync(), isTrue, reason: '$file does not exist');
      }
    });

    test('engine, reconcile and store run their whole directory', () {
      // None of the three has a same-name test: their behaviour is spread over
      // a directory of them. Scoped to a single file, every mutant would
      // "survive" and the report would be noise.
      final run = plan([
        'lib/src/sync/engine.dart',
        'lib/src/sync/reconcile.dart',
        'lib/src/store/store.dart',
      ]);

      expect(run.exitCode, 0, reason: run.stderr as String);
      expect((run.stdout as String).trim().split('\n'), [
        'lib/src/sync/engine.dart: flutter test test/sync',
        'lib/src/sync/reconcile.dart: flutter test test/sync',
        'lib/src/store/store.dart: flutter test test/store',
      ]);
    });

    test('a target that is not a source file stops the run', () {
      final run = plan(['lib/src/model/no_such_file.dart']);

      expect(run.exitCode, 2);
      expect(
        run.stderr,
        contains('not a file: lib/src/model/no_such_file.dart'),
      );
    });
  });
}
